# Generated by Django 3.2 on 2023-03-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_fees_in_world_movie_fess_in_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actors/'),
        ),
    ]
